### ISSUE TITLE
What does the gray open access color indicate?

### ISSUE THREAD

**Issue by dhimmel** [Impactstory/oadoi-paper1#1]
We've begun working with the Unpaywall data available on [Zenodo](https://doi.org/10.5281/zenodo.837902) for our Sci-Hub Coverage Study (see https://github.com/greenelab/scihub-manuscript/issues/18).

We noticed 32 DOIs from `unpaywall_100k.csv.gz` have `oa_color_long` of `gray`. See [unpaywall-gray.tsv.txt](https://github.com/Impactstory/oadoi-paper1/files/1215444/unpaywall-gray.tsv.txt) for the Unpaywall DOIs colored gray.

What does "gray" mean?

**Comment by hpiwowar** [comment]
It was leftover from a previous coding scheme.  It means "closed".  Sorry about that!

Heather
