### ISSUE TITLE
DOI catalogs exceed 100,000 records

### ISSUE THREAD

**Issue by dhimmel** [Impactstory/oadoi-paper1#2]
I noticed in the [Zenodo release](https://doi.org/10.5281/zenodo.837902) that:

+ `unpaywall_100k.csv.gz` has 105,647 DOIs
+ `wos_100k.csv.gz` has 103,539 DOIs

The [study preprint](https://peerj.com/preprints/3119v1.pdf) indicates that each sample DOI catalog contained only 100,000 DOIs.

This isn't an issue for me, just wanted to make sure you're aware of this discrepancy.

**Comment by hpiwowar** [comment]
true!  Yup, the exact numbers didn't make it into the paper.  We lose a few of them in our analysis because they don't have years in crossref, so the numbers in our analysis are closer (though still not I think absolutely exactly) 100k.
